// ─── Channel Store Connection Types ──────────────────────────────────────────
// Corresponds to the channel_store_connections MongoDB collection

export type ChannelType =
  | "shopify"
  | "wix"
  | "amazon"
  | "ebay"
  | "tiktok"
  | "lazada"
  | "tokopedia"
  | "facebook"
  | "shopee"
  | "walmart";

export interface ChannelStoreConnection {
  storeId: string;
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  region?: string;
  organizationId: string;
  /** Credentials are masked ("***MASKED***") in API responses */
  credentials: Record<string, string>;
  isActive: boolean;
  displayOrder: number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  connectedAt: string | number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  lastSyncedAt?: string | number;
}

export interface StoreConnectionRequest {
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  storeId?: string;
  region?: string;
  displayOrder?: number;
  credentials: Record<string, string>;
}

// ─── Channel Product Data Types ───────────────────────────────────────────────
// Corresponds to the channel_product_data MongoDB collection

export type ChannelProductStatus = "DRAFT" | "READY" | "PUBLISHED" | "FAILED";

export interface ChannelProductData {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  organizationId: string;
  status: ChannelProductStatus;
  /** Per-field overrides of master product data for this channel (keys with null = reset to master) */
  masterOverrides: Record<string, unknown>;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
  completionPercentage: number;
  readyToPublish: boolean;
  publishedAt?: string;
  publishError?: string;
  savedAt: string;
}

export interface ChannelStepSaveRequest {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  /** Per-field overrides of master product data for this channel; keys absent = inheriting master */
  masterOverrides: Record<string, unknown>;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
}

// ─── Completion Summary ───────────────────────────────────────────────────────

export interface StoreCompletionEntry {
  storeId: string;
  storeName: string;
  channelType: ChannelType;
  completionPercentage: number;
  status: ChannelProductStatus;
}

export interface CompletionSummaryResponse {
  overallReady: boolean;
  stores: StoreCompletionEntry[];
}

// ─── Step 2 Schema Types ──────────────────────────────────────────────────────
// Schema generated by POST /api/v1/ecommerce/form-schema/channel-step

export type ChannelFieldType =
  | "TEXT"
  | "TEXTAREA"
  | "NUMBER"
  | "SELECT"
  | "MULTISELECT"
  | "CHECKBOX"
  | "RADIO"
  | "DATE"
  | "URL"
  | "EMAIL"
  | "COLOR";

export interface ChannelFormField {
  fieldName: string;
  fieldType: ChannelFieldType;
  label: string;
  required: boolean;
  helpText?: string;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
  validationRules?: {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    min?: number;
    max?: number;
  };
  currentValue?: unknown;
  /** true = this field is driven from EcommerceMasterAttributeDocument.isChannelOverridable */
  isMasterField?: boolean;
  /** master product's current value for this field, resolved by backend at schema-gen time */
  masterValue?: unknown;
}

export interface VariantOverrideRow {
  sku: string;
  variantLabel: string;
  currentOverrides: Record<string, unknown>;
}

export type SectionName =
  | "required"
  | "recommended"
  | "variant_overrides"
  | "optional"
  | "master_overrides";

// ─── Master Product Snapshot ─────────────────────────────────────────────────
// Lightweight view of master product sent in ChannelStepSchemaResponse (Step 2)

export interface MasterProductSnapshot {
  name: string;
  description?: string;
  price: number;
  compareAtPrice?: number;
  quantity?: number;
  sku?: string;
  weight?: number;
  dimensions?: { length: number; width: number; height: number; unit: string };
  mainImage?: string;
  variants?: Array<{
    sku: string;
    variantLabel: string;
    price?: number;
    quantity?: number;
  }>;
}

export interface ChannelFormSection {
  sectionName: SectionName;
  label: string;
  priority: number;
  /** Only present when sectionName = "variant_overrides" */
  displayAs?: "TABLE";
  fields?: ChannelFormField[];
  /** Only for variant_overrides section */
  variantFields?: ChannelFormField[];
  variants?: VariantOverrideRow[];
}

export interface CompletionStats {
  requiredTotal: number;
  requiredFilled: number;
}

export interface ChannelSchemaPerStore {
  channelType: ChannelType;
  storeId: string;
  storeName: string;
  storeUrl: string;
  displayOrder: number;
  completionStatus: ChannelProductStatus;
  completionPercentage: number;
  sections: ChannelFormSection[];
  completionStats: CompletionStats;
}

export interface ChannelStepSchemaResponse {
  step: 2;
  masterProductId: string;
  /** Snapshot of master product fields sent by backend for display & override UX */
  masterProduct?: MasterProductSnapshot;
  channels: ChannelSchemaPerStore[];
}

export interface ChannelStepRequest {
  masterProductId: string;
  organizationId: string;
  masterVariants?: Array<{ sku: string; label: string }>;
}

// ─── Publish Types ────────────────────────────────────────────────────────────

export interface PublishSingleRequest {
  masterProductId: string;
  storeId: string;
  organizationId: string;
  /** Full flattened master product fields — required by backend to merge Step 2 channel data into */
  masterProductData?: Record<string, unknown>;
  /** Channel type, e.g. "shopify" — used by backend for routing and JOLT lookup */
  channelId?: string;
  /** Field mappings from pattern matching analysis (optional — backend uses stored JOLT if omitted) */
  fieldMappings?: unknown[];
  /** JOLT spec (optional — backend uses stored JOLT if omitted) */
  joltSpec?: unknown[];
  categoryId?: string;
  dryRun?: boolean;
}

export interface StorePublishResult {
  storeId: string;
  storeName?: string;
  status: "PUBLISHED" | "FAILED";
  publishedAt?: string;
  error?: string;
}

export interface BatchPublishRequest {
  masterProductId: string;
  organizationId: string;
  storeIds: string[];
}

export interface BatchPublishResponse {
  batchId: string;
  masterProductId: string;
  results: StorePublishResult[];
}

// ─── Publish Analysis Types ────────────────────────────────────────────────────
// POST /api/v1/channels/publish/analyze

export interface PublishAnalysisRequest {
  masterProductId: string;
  storeId: string;
  organizationId: string;
}

export interface MasterProductStageAnalysis {
  found: boolean;
  source: string;
  fieldCount: number;
  variantCount: number;
}

export interface ChannelDataStageAnalysis {
  completionPercentage: number;
  totalChannelFields: number;
  filledRequired: number;
  missingRequired: number;
  missingRequiredFields: string[];
}

export interface MergedInputStageAnalysis {
  fieldCount: number;
  fields: Record<string, unknown>;
}

export interface JoltSpecStageAnalysis {
  found: boolean;
  source: string;
  version?: string;
  operationCount: number;
}

export interface TransformationStageAnalysis {
  success: boolean;
  error?: string;
  topLevelKeys: string[];
  unmappedInputFields: string[];
  transformedData?: Record<string, unknown>;
}

export interface PostProcessingRuleDetail {
  priority: number;
  enabled: boolean;
  sourcePath: string;
  targetPath: string;
  description?: string;
}

export interface PostProcessingStageAnalysis {
  ruleCount: number;
  rules: PostProcessingRuleDetail[];
}

export interface AnalysisIssue {
  severity: "ERROR" | "WARNING" | "INFO";
  stage: string;
  message: string;
  field?: string;
}

export interface PublishAnalysisResponse {
  masterProductId: string;
  storeId: string;
  organizationId: string;
  readinessScore: number;
  issues: AnalysisIssue[];
  masterProduct: MasterProductStageAnalysis;
  channelData: ChannelDataStageAnalysis;
  mergedInput: MergedInputStageAnalysis;
  joltSpec: JoltSpecStageAnalysis;
  transformation: TransformationStageAnalysis;
  postProcessing: PostProcessingStageAnalysis;
}
