// ─── Channel Store Connection Types ──────────────────────────────────────────
// Corresponds to the channel_store_connections MongoDB collection

export type ChannelType =
  | "shopify"
  | "wix"
  | "amazon"
  | "ebay"
  | "tiktok"
  | "lazada"
  | "tokopedia"
  | "facebook"
  | "shopee"
  | "walmart";

export interface ChannelStoreConnection {
  storeId: string;
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  region?: string;
  organizationId: string;
  /** Credentials are masked ("***MASKED***") in API responses */
  credentials: Record<string, string>;
  isActive: boolean;
  displayOrder: number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  connectedAt: string | number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  lastSyncedAt?: string | number;
}

export interface StoreConnectionRequest {
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  storeId?: string;
  region?: string;
  displayOrder?: number;
  credentials: Record<string, string>;
}

// ─── Channel Product Data Types ───────────────────────────────────────────────
// Corresponds to the channel_product_data MongoDB collection

export type ChannelProductStatus = "DRAFT" | "READY" | "PUBLISHED" | "FAILED";

export interface ChannelProductData {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  organizationId: string;
  status: ChannelProductStatus;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
  completionPercentage: number;
  readyToPublish: boolean;
  publishedAt?: string;
  publishError?: string;
  savedAt: string;
}

export interface ChannelStepSaveRequest {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
}

// ─── Completion Summary ───────────────────────────────────────────────────────

export interface StoreCompletionEntry {
  storeId: string;
  storeName: string;
  channelType: ChannelType;
  completionPercentage: number;
  status: ChannelProductStatus;
}

export interface CompletionSummaryResponse {
  overallReady: boolean;
  stores: StoreCompletionEntry[];
}

// ─── Step 2 Schema Types ──────────────────────────────────────────────────────
// Schema generated by POST /api/v1/ecommerce/form-schema/channel-step

export type ChannelFieldType =
  | "TEXT"
  | "TEXTAREA"
  | "NUMBER"
  | "SELECT"
  | "MULTISELECT"
  | "CHECKBOX"
  | "RADIO"
  | "DATE"
  | "URL"
  | "EMAIL"
  | "COLOR";

export interface ChannelFormField {
  fieldName: string;
  fieldType: ChannelFieldType;
  label: string;
  required: boolean;
  helpText?: string;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
  validationRules?: {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    min?: number;
    max?: number;
  };
  currentValue?: unknown;
}

export interface VariantOverrideRow {
  sku: string;
  variantLabel: string;
  currentOverrides: Record<string, unknown>;
}

export type SectionName = "required" | "recommended" | "variant_overrides" | "optional";

export interface ChannelFormSection {
  sectionName: SectionName;
  label: string;
  priority: number;
  /** Only present when sectionName = "variant_overrides" */
  displayAs?: "TABLE";
  fields?: ChannelFormField[];
  /** Only for variant_overrides section */
  variantFields?: ChannelFormField[];
  variants?: VariantOverrideRow[];
}

export interface CompletionStats {
  requiredTotal: number;
  requiredFilled: number;
}

export interface ChannelSchemaPerStore {
  channelType: ChannelType;
  storeId: string;
  storeName: string;
  storeUrl: string;
  displayOrder: number;
  completionStatus: ChannelProductStatus;
  completionPercentage: number;
  sections: ChannelFormSection[];
  completionStats: CompletionStats;
}

export interface ChannelStepSchemaResponse {
  step: 2;
  masterProductId: string;
  channels: ChannelSchemaPerStore[];
}

export interface ChannelStepRequest {
  masterProductId: string;
  organizationId: string;
  masterVariants?: Array<{ sku: string; label: string }>;
}

// ─── Publish Types ────────────────────────────────────────────────────────────

export interface PublishSingleRequest {
  masterProductId: string;
  storeId: string;
  organizationId: string;
}

export interface StorePublishResult {
  storeId: string;
  storeName?: string;
  status: "PUBLISHED" | "FAILED";
  publishedAt?: string;
  error?: string;
}

export interface BatchPublishRequest {
  masterProductId: string;
  organizationId: string;
  storeIds: string[];
}

export interface BatchPublishResponse {
  batchId: string;
  masterProductId: string;
  results: StorePublishResult[];
}
