// ─── Channel Store Connection Types ──────────────────────────────────────────
// Corresponds to the channel_store_connections MongoDB collection

export type ChannelType =
  | "shopify"
  | "wix"
  | "amazon"
  | "ebay"
  | "tiktok"
  | "lazada"
  | "tokopedia"
  | "facebook"
  | "shopee"
  | "walmart";

/** Phase E: connection lifecycle status derived by backend from isActive + reconnectRequired + disconnectReason */
export type ConnectionStatus = 'ACTIVE' | 'RECONNECT_REQUIRED' | 'DISCONNECTED' | 'INACTIVE';

export interface ChannelStoreConnection {
  storeId: string;
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  region?: string;
  organizationId: string;
  /** Credentials are masked ("***MASKED***") in API responses */
  credentials: Record<string, string>;
  isActive: boolean;
  displayOrder: number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  connectedAt: string | number;
  /** ISO 8601 string or epoch-seconds number depending on backend Jackson config */
  lastSyncedAt?: string | number;

  // ── Phase D + E new fields ──────────────────────────────────────────────
  /** Phase E: true when the OAuth token has expired/been revoked — merchant must re-authorize */
  reconnectRequired?: boolean;
  /** Phase E: derived status — drives badge color and action buttons in the UI */
  connectionStatus?: ConnectionStatus;
  /** Phase D: ISO datetime when the store was deactivated by a marketplace webhook */
  disconnectedAt?: string;
  /** Phase D: machine-readable reason ("app_uninstalled" | "deauthorize" | "app_removed" | "manual" | …) */
  disconnectReason?: string;
}

/**
 * One credential field in a connect-store or update-credentials request.
 * Mirrors the backend CredentialEntry DTO.
 *
 * credId       — matches CredentialFieldSchema.credId (backend schema identifier)
 * chnlCredName — becomes the key in the stored credentials map (e.g. "accessToken")
 * chnlCredValue — the actual secret value
 */
export interface CredentialEntry {
  credId: string;
  chnlCredName: string;
  chnlCredValue: string;
}

export interface StoreConnectionRequest {
  channelType: ChannelType;
  storeName: string;
  storeUrl: string;
  storeId?: string;
  region?: string;
  displayOrder?: number;
  /** Structured credential list — each entry maps credId → chnlCredName → value */
  credentials: CredentialEntry[];
}

// ─── Credential Schema Types ──────────────────────────────────────────────────
// Returned by GET /api/v1/channel-stores/credential-schema/{channelType}

export interface CredentialFieldSchema {
  /** Backend internal identifier — used as the key in the structured credentials payload */
  credId: string;
  /** Canonical credential name — used as the key in Record<string,string> credentials map */
  chnlCredName: string;
  label: string;
  inputType: "text" | "password" | "email" | "url" | "number";
  sensitive: boolean;
  required: boolean;
  helpText?: string;
}

// ─── Channel Product Data Types ───────────────────────────────────────────────
// Corresponds to the channel_product_data MongoDB collection

export type ChannelProductStatus = "DRAFT" | "READY" | "PUBLISHED" | "FAILED";

export interface ChannelProductData {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  organizationId: string;
  status: ChannelProductStatus;
  /** Per-field overrides of master product data for this channel (keys with null = reset to master) */
  masterOverrides: Record<string, unknown>;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
  completionPercentage: number;
  readyToPublish: boolean;
  publishedAt?: string;
  publishError?: string;
  savedAt: string;
}

export interface ChannelStepSaveRequest {
  masterProductId: string;
  storeId: string;
  channelType: ChannelType;
  /** Per-field overrides of master product data for this channel; keys absent = inheriting master */
  masterOverrides: Record<string, unknown>;
  channelData: Record<string, unknown>;
  variantOverrides: Record<string, Record<string, unknown>>;
}

// ─── Completion Summary ───────────────────────────────────────────────────────

export interface StoreCompletionEntry {
  storeId: string;
  storeName: string;
  channelType: ChannelType;
  completionPercentage: number;
  status: ChannelProductStatus;
}

export interface CompletionSummaryResponse {
  overallReady: boolean;
  stores: StoreCompletionEntry[];
}

// ─── Step 2 Schema Types ──────────────────────────────────────────────────────
// Schema generated by POST /api/v1/ecommerce/form-schema/channel-step

export type ChannelFieldType =
  | "TEXT"
  | "TEXTAREA"
  | "NUMBER"
  | "SELECT"
  | "MULTISELECT"
  | "CHECKBOX"
  | "RADIO"
  | "DATE"
  | "URL"
  | "EMAIL"
  | "COLOR";

export interface ChannelFormField {
  fieldName: string;
  fieldType: ChannelFieldType;
  label: string;
  required: boolean;
  helpText?: string;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
  validationRules?: {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    min?: number;
    max?: number;
  };
  currentValue?: unknown;
  /** true = this field is driven from EcommerceMasterAttributeDocument.isChannelOverridable */
  isMasterField?: boolean;
  /** master product's current value for this field, resolved by backend at schema-gen time */
  masterValue?: unknown;
  // ── Scenario A: Merchant-sourced options ──────────────────────────────────
  /**
   * STATIC   = options[] is complete and static — no fetch needed (default).
   * MERCHANT_API = options are live from the merchant's account.
   *   - Eager embed: backend called the channel API during schema generation and
   *     embedded results in options[]. Frontend requires no changes.
   *   - Lazy load: options[] is empty; backend sets optionsEndpoint so the
   *     frontend fetches when the field is rendered.
   */
  optionsSource?: "STATIC" | "MERCHANT_API";
  /**
   * Relative URL pre-built by the backend for lazy-load fields.
   * Example: /merchant-data/shopify/store-abc/field-options?fieldName=location_id&organizationId=org_123
   * Only present when optionsSource === "MERCHANT_API" and options[] is empty (lazy path).
   */
  optionsEndpoint?: string;
}

export interface VariantOverrideRow {
  sku: string;
  variantLabel: string;
  currentOverrides: Record<string, unknown>;
}

export type SectionName =
  | "required"
  | "recommended"
  | "variant_overrides"
  | "optional"
  | "master_overrides"
  /** Scenario A: fields whose options come from the merchant's live account (warehouses, shipping templates, etc.) */
  | "merchant_data";

// ─── Master Product Snapshot ─────────────────────────────────────────────────
// Lightweight view of master product sent in ChannelStepSchemaResponse (Step 2)

export interface MasterProductSnapshot {
  name: string;
  description?: string;
  price: number;
  compareAtPrice?: number;
  quantity?: number;
  sku?: string;
  weight?: number;
  dimensions?: { length: number; width: number; height: number; unit: string };
  mainImage?: string;
  variants?: Array<{
    sku: string;
    variantLabel: string;
    /** All master variant attributes — open map so any fieldName resolves correctly in the variant table */
    [fieldName: string]: unknown;
  }>;
}

export interface ChannelFormSection {
  sectionName: SectionName;
  label: string;
  priority: number;
  /** Only present when sectionName = "variant_overrides" */
  displayAs?: "TABLE";
  fields?: ChannelFormField[];
  /** Only for variant_overrides section */
  variantFields?: ChannelFormField[];
  variants?: VariantOverrideRow[];
}

export interface CompletionStats {
  requiredTotal: number;
  requiredFilled: number;
}

export interface ChannelSchemaPerStore {
  channelType: ChannelType;
  storeId: string;
  storeName: string;
  storeUrl: string;
  displayOrder: number;
  completionStatus: ChannelProductStatus;
  completionPercentage: number;
  sections: ChannelFormSection[];
  completionStats: CompletionStats;
}

export interface ChannelStepSchemaResponse {
  step: 2;
  masterProductId: string;
  /** Snapshot of master product fields sent by backend for display & override UX */
  masterProduct?: MasterProductSnapshot;
  channels: ChannelSchemaPerStore[];
}

export interface ChannelStepRequest {
  masterProductId: string;
  organizationId: string;
  masterVariants?: Array<{ sku: string; label: string }>;
}

// ─── OAuth Initiation Types (Phase B) ────────────────────────────────────────
// Frontend calls GET /api/v1/oauth/initiate → gets authorizationUrl → redirects browser

export interface OAuthInitiateRequest {
  channelType: ChannelType;
  organizationId: string;
  storeName: string;
  region?: string;
  /** Required for Shopify — the {yourstore}.myshopify.com domain */
  shop?: string;
  /** For reconnect flow — backend uses this to update existing store record instead of creating new */
  storeId?: string;
}

export interface OAuthInitiateResponse {
  authorizationUrl: string;
  nonce: string;
  channelType: ChannelType;
}

// ─── Publish Types ────────────────────────────────────────────────────────────

export interface PublishSingleRequest {
  masterProductId: string;
  storeId: string;
  organizationId: string;
  /** Full flattened master product fields — required by backend to merge Step 2 channel data into */
  masterProductData?: Record<string, unknown>;
  /** Channel type, e.g. "shopify" — used by backend for routing and JOLT lookup */
  channelId?: string;
  /** Field mappings from pattern matching analysis (optional — backend uses stored JOLT if omitted) */
  fieldMappings?: unknown[];
  /** JOLT spec (optional — backend uses stored JOLT if omitted) */
  joltSpec?: unknown[];
  categoryId?: string;
  dryRun?: boolean;
  /** Per-SKU variant field overrides from Step 2 variant table — forwarded to backend post-JOLT merge */
  variantOverrides?: Record<string, Record<string, unknown>>;
  /** Per-channel master field overrides from Step 2 master override section */
  masterOverrides?: Record<string, unknown>;
}

export interface StorePublishResult {
  storeId: string;
  storeName?: string;
  status: "PUBLISHED" | "FAILED";
  publishedAt?: string;
  error?: string;
}

export interface BatchPublishRequest {
  masterProductId: string;
  organizationId: string;
  storeIds: string[];
}

export interface BatchPublishResponse {
  batchId: string;
  masterProductId: string;
  results: StorePublishResult[];
}

// ─── Publish Analysis Types ────────────────────────────────────────────────────
// POST /api/v1/channels/publish/analyze

export interface PublishAnalysisRequest {
  masterProductId: string;
  storeId: string;
  organizationId: string;
}

export interface MasterProductStageAnalysis {
  found: boolean;
  source: string;
  fieldCount: number;
  variantCount: number;
}

export interface ChannelDataStageAnalysis {
  completionPercentage: number;
  totalChannelFields: number;
  filledRequired: number;
  missingRequired: number;
  missingRequiredFields: string[];
}

export interface MergedInputStageAnalysis {
  fieldCount: number;
  fields: Record<string, unknown>;
}

export interface JoltSpecStageAnalysis {
  found: boolean;
  source: string;
  version?: string;
  operationCount: number;
}

export interface TransformationStageAnalysis {
  success: boolean;
  error?: string;
  topLevelKeys: string[];
  unmappedInputFields: string[];
  transformedData?: Record<string, unknown>;
}

export interface PostProcessingRuleDetail {
  priority: number;
  enabled: boolean;
  sourcePath: string;
  targetPath: string;
  description?: string;
}

export interface PostProcessingStageAnalysis {
  ruleCount: number;
  rules: PostProcessingRuleDetail[];
}

export interface AnalysisIssue {
  severity: "ERROR" | "WARNING" | "INFO";
  stage: string;
  message: string;
  field?: string;
}

export interface PublishAnalysisResponse {
  masterProductId: string;
  storeId: string;
  organizationId: string;
  readinessScore: number;
  issues: AnalysisIssue[];
  masterProduct: MasterProductStageAnalysis;
  channelData: ChannelDataStageAnalysis;
  mergedInput: MergedInputStageAnalysis;
  joltSpec: JoltSpecStageAnalysis;
  transformation: TransformationStageAnalysis;
  postProcessing: PostProcessingStageAnalysis;
}
